# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Description of what the lane does'
  lane :build_and_test do
    sendMessage('Started building', true)
    begin
       build_and_test_lane
    rescue StandardError => e
      on_error(e)
     end
  end
  def build_and_test_lane
    xcbuild
    run_tests(device: 'iPhone 8 Plus')
    sendMessage('Built success', true)
  end

  def on_error(exception)
    sendMessage("Lane failed with exception : #{exception}", false)
  end

  def sendMessage(messageText, success)
    slack(
      message: messageText,
      success: success,
      slack_url: 'https://hooks.slack.com/services/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',
      payload: { # Optional, lets you specify any number of your own Slack attachments.
        'Build Date' => Time.new.to_s,
        'Target' => 'homeTask1_MVVMC_v2'
      },
      default_payloads: %i[git_branch git_author], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
      attachment_properties: {
        fields: [
          {
            title: 'Build number',
            value: get_version_number
          }
        ]
      }
    )
  end
end
